<?php

namespace AppBundle\Repository;

use AppBundle\Entity\Baptism;

/**
 * BaptemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaptismRepository extends \Doctrine\ORM\EntityRepository
{
}
