<?php

namespace AppBundle\Repository;

/**
 * BaptemHasUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaptemHasUserRepository extends \Doctrine\ORM\EntityRepository
{
}
