<?php

namespace AppBundle\Repository;

/**
 * PriceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * This function finds out the price of a product
     * @param $productName
     * @return array
     */
    public function findByProduct($productName){
        return $this
            ->createQueryBuilder('price')
            ->select('price')
            ->innerjoin('price.product', 'product')
            ->where('product.name = :productName')
            ->setParameter("productName", $productName)
            ->getQuery()
            ->getResult();
    }

}
