<?php

namespace AppBundle\Repository;

/**
 * RestaurantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RestaurantRepository extends \Doctrine\ORM\EntityRepository
{
    public function findRestaurantListCity ($cityName, $zipCode)
    {
        $query = $this->createQueryBuilder('r')
           ->where('r.city = :city')
           ->setParameter('city', $cityName)
           ->andWhere('r.postalCode = :zipCode')
           ->setParameter('zipCode',$zipCode)
           ->getQuery();

       return $query->getResult();
    }

    public function findSixthFirstRestaurants()
    {
        return $this->createQueryBuilder('r')
            ->select('r')
            ->setMaxResults(6)
            ->getQuery()
            ->getResult();
    }
}
