<?php

namespace AppBundle\Repository;

/**
 * ServiceOpeningRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceOpeningRepository extends \Doctrine\ORM\EntityRepository
{
}
